name: orbit-agent
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - openai
    - lightweight-charts
    - langchain
    - google-search-results
    - yfinance
    - beautifulsoup4
    - transformers
    - torch
    - tensorflow-macos
    - tensorflow-metal
    - keras
    - accelerate
    - statsmodels
